name = "learnova-backend"
main = "src/index.js"
compatibility_date = "2026-08-19"

[[containers]]
class_name = "LearnovaBackend"
image = "./Dockerfile"
max_instances = 5

[[durable_objects.bindings]]
name = "LEARNOVA_BACKEND"
class_name = "LearnovaBackend"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["LearnovaBackend"]
