'use client';

import { useWorkspaceStore } from '@/store/workspaceStore';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { api } from '@/lib/api';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { CheckCircle, XCircle, AlertCircle } from 'lucide-react';
import { notify } from '@/store/notificationStore';
import { useSearchParams } from 'next/navigation';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';

export default function ReviewPage() {
  const { examId, subjectId } = useWorkspaceStore();
  const searchParams = useSearchParams();
  const sessionId = searchParams.get('session_id');
  const queryClient = useQueryClient();

  const { data: questions = [], isLoading } = useQuery({
    queryKey: ['pending_questions', examId, subjectId, sessionId],
    queryFn: async () => {
      let url = `/api/v1/generation/questions?status=PENDING`;
      if (examId) url += `&exam_id=${examId}`;
      if (subjectId) url += `&subject_id=${subjectId}`;
      if (sessionId) url += `&session_id=${sessionId}`;
      const res = await api.get(url);
      return res.data;
    },
    enabled: !!examId && !!subjectId,
  });

  const approveMutation = useMutation({
    mutationFn: (id: string) => api.post(`/api/v1/generation/questions/${id}/approve`),
    onSuccess: () => {
      notify.success('Question approved and added to Question Bank');
      queryClient.invalidateQueries({ queryKey: ['pending_questions'] });
    },
    onError: () => notify.error('Failed to approve question')
  });

  const rejectMutation = useMutation({
    mutationFn: (id: string) => api.post(`/api/v1/generation/questions/${id}/reject`),
    onSuccess: () => {
      notify.info('Question rejected');
      queryClient.invalidateQueries({ queryKey: ['pending_questions'] });
    },
    onError: () => notify.error('Failed to reject question')
  });

  const bulkApproveMutation = useMutation({
    mutationFn: (ids: string[]) => api.post(`/api/v1/generation/questions/bulk-approve`, { question_ids: ids }),
    onSuccess: (data) => {
      notify.success(`Successfully approved ${data.data.count} questions`);
      queryClient.invalidateQueries({ queryKey: ['pending_questions'] });
    },
    onError: () => notify.error('Failed to bulk approve questions')
  });

  const bulkRejectMutation = useMutation({
    mutationFn: (ids: string[]) => api.post(`/api/v1/generation/questions/bulk-reject`, { question_ids: ids }),
    onSuccess: (data) => {
      notify.info(`Successfully rejected ${data.data.count} questions`);
      queryClient.invalidateQueries({ queryKey: ['pending_questions'] });
    },
    onError: () => notify.error('Failed to bulk reject questions')
  });

  if (!examId || !subjectId) {
    return (
      <div className="p-8 max-w-7xl mx-auto space-y-6">
        <h1 className="text-3xl font-bold tracking-tight">Review Pending Questions</h1>
        <Alert variant="default" className="bg-amber-50 text-amber-800 border-amber-200">
          <AlertCircle className="h-4 w-4" />
          <AlertTitle>Context Required</AlertTitle>
          <AlertDescription>
            Please select an Exam and Subject from the sidebar to view pending questions.
          </AlertDescription>
        </Alert>
      </div>
    );
  }

  return (
    <div className="p-8 max-w-5xl mx-auto space-y-8 animate-in fade-in duration-500">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">Review Pending Questions</h1>
          <p className="text-muted-foreground mt-2">Approve or reject questions generated by the AI before adding them to the Question Bank.</p>
          {sessionId && (
            <Badge variant="secondary" className="mt-4">
              Filtering by recent generation session
            </Badge>
          )}
        </div>
        
        {!isLoading && questions.length > 0 && (
          <div className="flex items-center gap-3">
            <Button 
              variant="outline"
              className="text-red-600 hover:text-red-700 hover:bg-red-50 border-red-200"
              onClick={() => bulkRejectMutation.mutate(questions.map((q: any) => q.id))}
              disabled={bulkRejectMutation.isPending || bulkApproveMutation.isPending}
            >
              <XCircle className="w-4 h-4 mr-2" />
              Reject All
            </Button>
            <Button
              className="bg-green-600 hover:bg-green-700"
              onClick={() => bulkApproveMutation.mutate(questions.map((q: any) => q.id))}
              disabled={bulkRejectMutation.isPending || bulkApproveMutation.isPending}
            >
              <CheckCircle className="w-4 h-4 mr-2" />
              Approve All
            </Button>
          </div>
        )}
      </div>

      {isLoading ? (
        <div className="text-center py-12 text-muted-foreground border rounded-xl bg-card">Loading pending questions...</div>
      ) : questions.length === 0 ? (
        <div className="border rounded-xl p-12 text-center bg-card shadow-sm">
          <CheckCircle className="w-12 h-12 text-green-500 mx-auto mb-4 opacity-50" />
          <h3 className="text-lg font-semibold mb-2">All Caught Up!</h3>
          <p className="text-muted-foreground">There are no pending questions to review in this context.</p>
        </div>
      ) : (
        <div className="space-y-6">
          {questions.map((q: any, index: number) => {
            const hasOptions = q.content.options && Array.isArray(q.content.options) && q.content.options.length > 0;
            const session = q.session || {};
            
            return (
              <Card key={q.id} className="shadow-sm">
                <CardHeader className="bg-muted/30 pb-4 border-b">
                  <div className="flex justify-between items-start">
                    <div>
                      <CardTitle className="text-base flex items-center gap-2">
                        Question {index + 1}
                      </CardTitle>
                      <div className="flex gap-2 mt-2">
                        <Badge variant="outline" className="capitalize">{session.question_type || 'Unknown'}</Badge>
                        <Badge variant="outline" className="capitalize">{session.difficulty || 'Unknown'}</Badge>
                        <Badge variant="outline">{session.marks ? `${session.marks} Marks` : 'N/A'}</Badge>
                      </div>
                    </div>
                  </div>
                </CardHeader>
                <CardContent className="pt-6 space-y-4">
                  <div className="prose prose-sm max-w-none">
                    <p className="font-medium text-base text-card-foreground whitespace-pre-wrap">{q.question_text}</p>
                  </div>

                  {hasOptions && (
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-3 mt-4">
                      {q.content.options.map((opt: any) => {
                        const isCorrect = q.content.correct_answer === opt.id || q.content.correct_answer === opt.text;
                        return (
                          <div 
                            key={opt.id} 
                            className={`p-3 rounded-lg border text-sm flex gap-3 items-center ${
                              isCorrect 
                                ? 'bg-green-50/50 border-green-200 text-green-900 font-medium' 
                                : 'bg-muted/10 border-border text-muted-foreground'
                            }`}
                          >
                            <span className={`w-6 h-6 rounded-full flex items-center justify-center text-xs font-bold ${
                              isCorrect ? 'bg-green-500 text-white' : 'bg-muted text-muted-foreground'
                            }`}>
                              {opt.id}
                            </span>
                            <span>{opt.text}</span>
                          </div>
                        );
                      })}
                    </div>
                  )}

                  <div className="mt-4 p-4 bg-muted/20 border border-muted rounded-lg space-y-2 text-sm">
                    <div className="flex items-center gap-2 font-semibold text-emerald-800 dark:text-emerald-400">
                      <CheckCircle className="w-4 h-4 text-green-600" />
                      <span>Correct Answer: {q.content.correct_answer}</span>
                    </div>
                    {q.content.explanation && (
                      <div className="text-muted-foreground mt-1">
                        <span className="font-semibold text-foreground">Explanation:</span> {q.content.explanation}
                      </div>
                    )}
                    {q.content.source_citations && q.content.source_citations.length > 0 && (
                      <div className="text-xs text-muted-foreground pt-2 border-t border-muted flex flex-wrap gap-2">
                        <span className="font-medium">Sources Cited:</span>
                        {q.content.source_citations.map((cite: string, idx: number) => (
                          <Badge key={idx} variant="secondary" className="text-[10px] py-0 px-1.5">{cite}</Badge>
                        ))}
                      </div>
                    )}
                  </div>
                </CardContent>
                <CardFooter className="bg-muted/10 border-t p-4 flex justify-end gap-3">
                <Button 
                  variant="outline" 
                  className="text-red-600 hover:text-red-700 hover:bg-red-50 border-red-200"
                  onClick={() => rejectMutation.mutate(q.id)}
                  disabled={rejectMutation.isPending || approveMutation.isPending}
                >
                  <XCircle className="w-4 h-4 mr-2" />
                  Reject
                </Button>
                <Button 
                  className="bg-green-600 hover:bg-green-700"
                  onClick={() => approveMutation.mutate(q.id)}
                  disabled={rejectMutation.isPending || approveMutation.isPending}
                >
                  <CheckCircle className="w-4 h-4 mr-2" />
                  Approve & Add to Bank
                </Button>
              </CardFooter>
              </Card>
            );
          })}
        </div>
      )}
    </div>
  );
}
