"""Add created_by and description to Exam

Revision ID: 0adc4324d44f
Revises: 312d7c3f3f83
Create Date: 2026-08-11 21:16:12.831499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0adc4324d44f'
down_revision: Union[str, Sequence[str], None] = '312d7c3f3f83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exams', sa.Column('exam_type', sa.String(), nullable=True))
    op.add_column('exams', sa.Column('description', sa.String(), nullable=True))
    op.add_column('exams', sa.Column('created_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'exams', 'profiles', ['created_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exams', type_='foreignkey')
    op.drop_column('exams', 'created_by')
    op.drop_column('exams', 'description')
    op.drop_column('exams', 'exam_type')
    # ### end Alembic commands ###
