"""phase11_quality_tracking

Revision ID: 4c6f69ddf127
Revises: befc764e85f6
Create Date: 2026-08-09 20:55:11.158807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4c6f69ddf127'
down_revision: Union[str, Sequence[str], None] = 'befc764e85f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_papers', sa.Column('quality_report', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('question_papers', sa.Column('quality_status', sa.String(), nullable=True))
    op.add_column('question_papers', sa.Column('quality_checked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('question_papers', sa.Column('quality_report_stale', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question_papers', 'quality_report_stale')
    op.drop_column('question_papers', 'quality_checked_at')
    op.drop_column('question_papers', 'quality_status')
    op.drop_column('question_papers', 'quality_report')
    # ### end Alembic commands ###
