"""phase4_document_chunks

Revision ID: 93981de91e87
Revises: 9c026aac11c0
Create Date: 2026-08-09 16:35:36.851759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '93981de91e87'
down_revision: Union[str, Sequence[str], None] = '9c026aac11c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Enable pgvector
    op.execute('CREATE EXTENSION IF NOT EXISTS vector;')
    
    # 2. Update ResourceStatus Enum
    # In some psycopg2 setups, we must do this:
    try:
        op.execute("ALTER TYPE resourcestatus ADD VALUE IF NOT EXISTS 'EXTRACTING'")
        op.execute("ALTER TYPE resourcestatus ADD VALUE IF NOT EXISTS 'OCR'")
        op.execute("ALTER TYPE resourcestatus ADD VALUE IF NOT EXISTS 'CHUNKING'")
        op.execute("ALTER TYPE resourcestatus ADD VALUE IF NOT EXISTS 'EMBEDDING'")
    except Exception as e:
        print(f"Enum update error (might already exist): {e}")
        pass

    op.create_table('document_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=384), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_resource_id'), 'document_chunks', ['resource_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_chunks_resource_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    
    op.execute('DROP EXTENSION IF EXISTS vector;')
    # Note: downgrading ENUMs is notoriously difficult in Postgres and usually not needed
    # ### end Alembic commands ###
