"""Add pattern_id to GenerationSession

Revision ID: 96ecfb2cc896
Revises: 78f8ce856313
Create Date: 2026-08-11 18:34:09.885475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96ecfb2cc896'
down_revision: Union[str, Sequence[str], None] = '78f8ce856313'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generation_sessions', sa.Column('pattern_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'generation_sessions', 'exam_patterns', ['pattern_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'generation_sessions', type_='foreignkey')
    op.drop_column('generation_sessions', 'pattern_id')
    # ### end Alembic commands ###
