"""Add code and description to Subject

Revision ID: 9caff010d7b0
Revises: 0adc4324d44f
Create Date: 2026-08-11 21:18:05.570780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9caff010d7b0'
down_revision: Union[str, Sequence[str], None] = '0adc4324d44f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('code', sa.String(), nullable=True))
    op.add_column('subjects', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subjects', 'description')
    op.drop_column('subjects', 'code')
    # ### end Alembic commands ###
