"""phase7_batch_tracking

Revision ID: befc764e85f6
Revises: d3b47a14ee38
Create Date: 2026-08-09 20:30:40.579434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'befc764e85f6'
down_revision: Union[str, Sequence[str], None] = 'd3b47a14ee38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generation_sessions', sa.Column('batch_size', sa.Integer(), nullable=False))
    op.add_column('generation_sessions', sa.Column('total_batches', sa.Integer(), nullable=False))
    op.add_column('generation_sessions', sa.Column('current_batch', sa.Integer(), nullable=False))
    op.add_column('generation_sessions', sa.Column('repair_count', sa.Integer(), nullable=False))
    op.add_column('generation_sessions', sa.Column('llm_call_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generation_sessions', 'llm_call_count')
    op.drop_column('generation_sessions', 'repair_count')
    op.drop_column('generation_sessions', 'current_batch')
    op.drop_column('generation_sessions', 'total_batches')
    op.drop_column('generation_sessions', 'batch_size')
    # ### end Alembic commands ###
