"""Add SharePermission model

Revision ID: e01c5bae638d
Revises: ce4f38a3b1c6
Create Date: 2026-08-13 09:51:13.115024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e01c5bae638d'
down_revision: Union[str, Sequence[str], None] = 'ce4f38a3b1c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('share_permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('shared_by_id', sa.UUID(), nullable=False),
    sa.Column('shared_with_id', sa.UUID(), nullable=False),
    sa.Column('permission', sa.Enum('VIEW', 'EDIT', 'OWNER', name='sharepermissionlevel'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['shared_by_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shared_with_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_id', 'shared_with_id', name='uix_share_permission_unique')
    )
    op.create_index(op.f('ix_share_permissions_entity_id'), 'share_permissions', ['entity_id'], unique=False)
    op.create_index(op.f('ix_share_permissions_entity_type'), 'share_permissions', ['entity_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_share_permissions_entity_type'), table_name='share_permissions')
    op.drop_index(op.f('ix_share_permissions_entity_id'), table_name='share_permissions')
    op.drop_table('share_permissions')
    # ### end Alembic commands ###
